# Stage 1: Build stage
FROM node:24-alpine AS builder

WORKDIR /app

# Install build dependencies for better-sqlite3
RUN apk add --no-cache python3 make g++

# Copy package management files
COPY package*.json ./

# Install ALL dependencies (including devDependencies needed for build)
RUN npm install

# Copy application source
COPY . .

# Build the Nuxt application
RUN npm run build

# Stage 2: Runtime stage
FROM node:24-alpine AS runner

WORKDIR /app

# Install runtime dependencies for better-sqlite3 if needed (it often needs libc compatibility on Alpine)
RUN apk add --no-cache python3 make g++

# Set environment variables
ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000

# Copy the built output from the builder stage
# Nuxt 3/4 builds to .output directory
COPY --from=builder /app/.output ./.output

# Copy package.json to the runner stage (optional but can be useful)
COPY --from=builder /app/package.json ./package.json

# Expose the production port
EXPOSE 3000

# Start the server using the entry point generated by Nitro
CMD ["node", ".output/server/index.mjs"]
